#
# InterChat | Discord and Telegram integration
#
# Documentation: (WIP)
# SpigotMC: https://www.spigotmc.org/threads/interchat-telegram-and-discord-integration-updates-full-free.566260/#post-4452346
# Github:
#
# Licensed under MIT.
#

media-view:
  enable: true
  hover: "<color:#7289da>RCM</color> <gray>to open attachments"

discord:
  token: "YOUR-TOKEN-HERE"
  enabled: false
  minecraft: "<color:#7289da>DISCORD</color> <color:#36393e>|</color> <color:{color}>{role} {name}</color> <color:#36393e>»</color> {message}"
  endpoint: "{name}: {message}"
  channel: 012345678910

telegram:
  token: "YOUR-TOKEN-HERE"
  enabled: false
  minecraft: "<color:#0088CC>TELEGRAM</color> <color:#36393e>|</color> {name} <color:#36393e>»</color> {message}"
  endpoint: "{name}: {message}"
  channel: "012345678910"
